### ISSUE TITLE
Host frontend website

### ISSUE THREAD

**Issue by cynical-cheddar** [Free-Pizza-Team-QA-LBG/QA_frontend#1]

**Comment by cynical-cheddar** [comment]
Decide on framework.
Host a frontend site.

Keep in mind connections with github actions for testing.
Consider Selenium.
Consider API Routes

**Comment by cynical-cheddar** [comment]
Host on GCP

**Comment by AlexPTerry** [comment]
GCP VM instance created free-pizza-frontend

**Comment by AlexPTerry** [comment]
Cloned frontend repo, created firewall rule to open access to port 3000 on GCP. Server can now be accessed at http://[ip]:3000
